GET http://localhost:3001/books HTTP/1.1
Content-Type: application/json

### 
### Response
POST http://localhost:3001/books HTTP/1.1
Content-Type: application/json

{
    "title": "The Lord of the Rings"
}

###
### PUT Request
PUT http://localhost:3001/books/1 HTTP/1.1
Content-Type: application/json

{
    "title": "The Lord of the Tings"
}

###
### DELETE Request
DELETE http://localhost:3001/books/1 HTTP/1.1
Content-Type: application/json
